### ISSUE TITLE
Update navbar

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/TrackIT#23]
Clean up the navbar
 - Remove dead links
 - Add link to acm website
 - Add link to acm instagram
 - Add link to acm github
 - Keep navbar tab for pricing (create a fake page with a couple of cards to show sample pricing) Eventually we will change this page to show how other organizations and groups can make use of our software. For now it can just be a nice visual
 - Add link on navbar for tutorial. This should redirect to a readme (refer to github issue #24 )

**Comment by aemmadi** [comment]
Fixed with #26
