### ISSUE TITLE
User Tests

### ISSUE THREAD

**Issue by sivampatel** [acmutd/TrackIT#57]
Use Jest to create testing suite for application utilizing Jest's snapshot testing functionality. 
Ex. loading up UserDashboard and expecting render to only show `<Spinner /> ` until another function is called. 

- [ ] Create at least one test case for every component
- [ ] User Dashboard tests manipulate object state to test React output
- [ ] User Dashboard tests to check functionality of "next", "previous", and "mark completed" buttons
- [ ] Tests check various buttons such as Sign Out and alerts. 
- [ ] ensure all tests are passed by the current version of the application

**Comment by harshasrikara** [comment]
Duplicate of #56
